# Generated by Django 6.0.4 on 2026-05-08 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('medium', models.CharField(choices=[('oil', 'Oil painting'), ('water', 'Watercolour Painting'), ('sculpture', 'Sculpture'), ('photo', 'Photography'), ('other', 'Other')], max_length=50)),
                ('style', models.CharField(choices=[('abstract', 'Abstract'), ('realism', 'Realism'), ('impressionism', 'Impressionism'), ('modern', 'Modern'), ('other', 'Other')], max_length=50)),
                ('starting_bid', models.PositiveIntegerField(default=0)),
                ('date_listed', models.DateField(auto_now_add=True)),
                ('sold', models.BooleanField(default=False)),
                ('dimensions', models.CharField(max_length=50)),
                ('year_created', models.PositiveIntegerField()),
                ('edition', models.CharField(max_length=50)),
                ('provenance', models.TextField()),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ArtworkImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='artwork/%Y/%m')),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='artworks.artwork')),
            ],
        ),
    ]
