# Generated by Django 6.0.4 on 2026-05-09 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artworkimage',
            name='image',
        ),
        migrations.AddField(
            model_name='artworkimage',
            name='image_path',
            field=models.CharField(default='artwork_images/placeholder.png', max_length=255),
            preserve_default=False,
        ),
    ]
