# Generated by Django 6.0.4 on 2026-05-10 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_address_seller'),
        ('artworks', '0002_remove_artworkimage_image_artworkimage_image_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artworks', to='accounts.seller'),
        ),
    ]
