# Generated by Django 6.0.4 on 2026-05-11 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0003_alter_artwork_seller'),
    ]

    operations = [
        migrations.RenameField(
            model_name="artworkimage",
            old_name="image_path",
            new_name="image",
        ),
        migrations.AlterField(
            model_name="artworkimage",
            name="image",
            field=models.ImageField(
                upload_to="artwork_images",
                blank=True,
                null=True,
            ),
        ),
    ]
