# Generated by Django 6.0.4 on 2026-05-11 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0003_alter_artwork_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artworkimage',
            name='image_path',
        ),
        migrations.AddField(
            model_name='artworkimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='artwork_images'),
        ),
    ]
