# Generated by Django 6.0.4 on 2026-05-13 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0004_remove_artworkimage_image_path_artworkimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='artist_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
