# Generated by Django 6.0.4 on 2026-05-13 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0005_artwork_artist_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='artist_name',
            field=models.CharField(max_length=255),
        ),
    ]
