# Generated by Django 6.0.4 on 2026-05-14 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0005_favorite'),
        ('artworks', '0006_alter_artwork_artist_name'),
    ]

    operations = [
    ]
