# Generated by Django 6.0.4 on 2026-05-10 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_address_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='cover_image',
            field=models.CharField(default='artwork_images/placeholder.avif', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='seller',
            name='logo',
            field=models.CharField(default='artwork_images/placeholder.avif', max_length=255),
            preserve_default=False,
        ),
    ]
