# Generated by Django 6.0.4 on 2026-05-11 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_seller_cover_image_alter_seller_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='country',
            field=models.CharField(choices=[('Iceland', 'Iceland'), ('Denmark', 'Denmark'), ('Norway', 'Norway'), ('Sweden', 'Sweden'), ('United Kingdom', 'United Kingdom'), ('United States', 'United States')], default='Iceland', max_length=20),
        ),
    ]
