# Generated by Django 6.0.4 on 2026-05-11 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_address_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='seller_images/covers'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='seller_images/logos'),
        ),
    ]
