<<<<<<< HEAD
# Generated by Django 6.0.4 on 2026-05-14 13:45
=======
# Generated by Django 6.0.4 on 2026-05-14 14:14
>>>>>>> 1cae0507d76a1f746c839346680ec7252ac99e04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_message'),
        ('accounts', '0006_notification'),
    ]

    operations = [
    ]
