# Generated by Django 6.0.4 on 2026-05-14 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_message'),
        ('accounts', '0006_notification'),
    ]

    operations = [
    ]
