# Generated by Django 6.0.4 on 2026-05-11 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_address_country'),
        ('bids', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('credit_card', 'Credit Card'), ('bank_transfer', 'Bank Transfer'), ('wire_transfer', 'Wire Transfer')], max_length=30)),
                ('cardholder', models.CharField(blank=True, max_length=30)),
                ('card_number', models.CharField(blank=True, max_length=30)),
                ('card_expiration', models.CharField(blank=True, max_length=30)),
                ('card_cvc', models.CharField(blank=True, max_length=30)),
                ('bank_account', models.CharField(blank=True, max_length=30)),
                ('bank_name', models.CharField(blank=True, max_length=30)),
                ('routing_number', models.CharField(blank=True, max_length=30)),
                ('account_number', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Finalization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id', models.CharField(blank=True, max_length=30)),
                ('date_finalized', models.DateField(blank=True, null=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finalization', to='accounts.address')),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finalization', to='bids.bid')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finalization', to='finalization.payment')),
            ],
        ),
    ]
